# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Steganography-Image-Png
version:      0.04
version_from: Png.pm
installdirs:  site
requires:
    Class::Accessor:               0
    Imager:                        0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
