--- #YAML:1.0
name:                Acme-Steganography-Image-Png
version:             0.06
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.30_02
author:              Nicholas Clark <nick@ccl4.org>
distribution_type:   module
requires:     
    Class::Accessor:               0
    Imager:                        0
    Test::More:                    0
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
